# Generated by Django 5.2.7 on 2025-12-22 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Химический_компонент',
            },
        ),
        migrations.CreateModel(
            name='ChemicalDesignationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Тип_химического_обозначения',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Элемент',
            },
        ),
        migrations.CreateModel(
            name='FillingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Способ_распыления',
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Газ',
            },
        ),
        migrations.CreateModel(
            name='GasMixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Газовая_смесь',
            },
        ),
        migrations.CreateModel(
            name='MetalWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_value', models.FloatField()),
                ('interval_min', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Металлическая_проволока',
            },
        ),
        migrations.CreateModel(
            name='ParticleShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Название_формы_частиц',
            },
        ),
        migrations.CreateModel(
            name='PowderClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Класс_пороха',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Название_свойства',
            },
        ),
        migrations.CreateModel(
            name='PropertyValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Тип_значения_свойства',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Единицы_измерения',
            },
        ),
        migrations.CreateModel(
            name='FillingMethodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bool_fil', models.BooleanField(default=False)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.fillingmethod')),
            ],
            options={
                'db_table': 'Метод_получения',
            },
        ),
        migrations.CreateModel(
            name='ChemicalDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_min', models.FloatField()),
                ('percent_max', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.chemicalcomponent')),
                ('designation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.chemicaldesignationtype')),
                ('gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.gas')),
            ],
            options={
                'db_table': 'Химическое_обозначение',
            },
        ),
        migrations.CreateModel(
            name='ElementalComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.FloatField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.element')),
                ('wire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.metalwire')),
            ],
            options={
                'db_table': 'Элементный_состав_проволоки',
            },
        ),
        migrations.CreateModel(
            name='PowderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filling_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.fillingmethodoption')),
                ('powder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powderclass')),
            ],
            options={
                'db_table': 'Вид_пороха',
            },
        ),
        migrations.CreateModel(
            name='PowderParticleShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.FloatField()),
                ('interval_min', models.FloatField(blank=True, null=True)),
                ('interval_max', models.FloatField(blank=True, null=True)),
                ('bool_par', models.BooleanField(default=False)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.particleshape')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype')),
            ],
            options={
                'db_table': 'Форма_частиц',
            },
        ),
        migrations.CreateModel(
            name='PowderAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_of', to='IACAPaaS_interactions.powdertype')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='IACAPaaS_interactions.powdertype')),
            ],
            options={
                'db_table': 'Аналоги_пороха',
            },
        ),
        migrations.CreateModel(
            name='PropertySynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.property')),
            ],
            options={
                'db_table': 'Синонимы_свойства',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.property')),
                ('property_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.propertyvaluetype')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IACAPaaS_interactions.unit')),
            ],
            options={
                'db_table': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='PowderProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype')),
                ('property_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.propertyvalue')),
            ],
            options={
                'db_table': 'Свойства_пороха',
            },
        ),
        migrations.CreateModel(
            name='MetalWireProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.metalwire')),
                ('property_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.propertyvalue')),
            ],
            options={
                'db_table': 'Свойства_металлической_проволоки',
            },
        ),
        migrations.AddField(
            model_name='metalwire',
            name='diameter_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit'),
        ),
        migrations.CreateModel(
            name='GranulometricComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('d10', models.FloatField()),
                ('d50', models.FloatField()),
                ('d90', models.FloatField()),
                ('average_value', models.FloatField()),
                ('mass_fraction', models.FloatField()),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit')),
            ],
            options={
                'db_table': 'Гранулометрический_состав',
            },
        ),
        migrations.CreateModel(
            name='GasMixtureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField()),
                ('gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.gas')),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.gasmixture')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit')),
            ],
            options={
                'db_table': 'Состав_газовой_смеси',
            },
        ),
        migrations.CreateModel(
            name='Flowability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('bool_fil', models.BooleanField(default=False)),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit')),
            ],
            options={
                'db_table': 'Текучесть_пороха',
            },
        ),
        migrations.CreateModel(
            name='BulkDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit')),
            ],
            options={
                'db_table': 'Насыпная_плотность_пороха',
            },
        ),
        migrations.CreateModel(
            name='WireAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_of', to='IACAPaaS_interactions.metalwire')),
                ('wire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='IACAPaaS_interactions.metalwire')),
            ],
            options={
                'db_table': 'Аналоги_проволоки',
            },
        ),
    ]
