# Generated by Django 5.2.7 on 2026-01-11 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50, verbose_name='Формула')),
            ],
            options={
                'verbose_name': 'Химический компонент',
                'verbose_name_plural': 'Химические компоненты',
            },
        ),
        migrations.CreateModel(
            name='ChemicalDesignationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип обозначения химсостава',
                'verbose_name_plural': 'Типы обозначений химсостава',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Химический элемент',
                'verbose_name_plural': 'Химические элементы',
            },
        ),
        migrations.CreateModel(
            name='FillingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Метод заполнения',
                'verbose_name_plural': 'Методы заполнения',
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gas', models.CharField(max_length=100, verbose_name='Название')),
                ('formula', models.CharField(max_length=50, verbose_name='Формула')),
                ('grade', models.CharField(max_length=50, verbose_name='Марка')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('standard', models.CharField(max_length=100, verbose_name='Стандарт')),
                ('adress_gas', models.CharField(max_length=200, verbose_name='Источник')),
                ('date_gas', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
            ],
            options={
                'verbose_name': 'Газ',
                'verbose_name_plural': 'Газы',
            },
        ),
        migrations.CreateModel(
            name='GasMixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100, verbose_name='Формула')),
                ('grade', models.CharField(max_length=50, verbose_name='Марка')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('standard', models.CharField(max_length=100, verbose_name='Стандарт')),
            ],
            options={
                'verbose_name': 'Газовая смесь',
                'verbose_name_plural': 'Газовые смеси',
            },
        ),
        migrations.CreateModel(
            name='MetalWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_value', models.FloatField(verbose_name='Диаметр')),
                ('interval', models.FloatField(blank=True, null=True, verbose_name='Интервал')),
            ],
            options={
                'verbose_name': 'Металлическая проволока',
                'verbose_name_plural': 'Металлическая проволока',
            },
        ),
        migrations.CreateModel(
            name='ParticleShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Форма частицы',
                'verbose_name_plural': 'Формы частиц',
            },
        ),
        migrations.CreateModel(
            name='PowderClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Класс порошка',
                'verbose_name_plural': 'Классы порошков',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='PropertyValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип значения свойства',
                'verbose_name_plural': 'Типы значений свойств',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='FillingMethodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название опции')),
                ('bool_fil', models.BooleanField(default=False, verbose_name='Флаг заполнения')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.fillingmethod', verbose_name='Метод заполнения')),
            ],
            options={
                'verbose_name': 'Опция метода заполнения',
                'verbose_name_plural': 'Опции методов заполнения',
            },
        ),
        migrations.CreateModel(
            name='ChemicalDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_value', models.FloatField(verbose_name='Мин. %')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.chemicalcomponent', verbose_name='Компонент')),
                ('designation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.chemicaldesignationtype', verbose_name='Тип обозначения')),
                ('gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.gas', verbose_name='Газ')),
            ],
            options={
                'verbose_name': 'Химическое обозначение газа',
                'verbose_name_plural': 'Химические обозначения газов',
            },
        ),
        migrations.CreateModel(
            name='ElementalComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.FloatField(verbose_name='Массовая доля')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.element', verbose_name='Элемент')),
                ('wire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.metalwire', verbose_name='Проволока')),
            ],
            options={
                'verbose_name': 'Элементный состав проволоки',
                'verbose_name_plural': 'Элементный состав проволоки',
            },
        ),
        migrations.CreateModel(
            name='PowderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_pow', models.CharField(max_length=200, verbose_name='Источник')),
                ('date_pow', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('filling_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.fillingmethodoption', verbose_name='Метод заполнения')),
                ('powder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powderclass', verbose_name='Класс порошка')),
            ],
            options={
                'verbose_name': 'Тип порошка',
                'verbose_name_plural': 'Типы порошков',
            },
        ),
        migrations.CreateModel(
            name='PowderParticleShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.FloatField(verbose_name='Размер')),
                ('value_powder', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('bool_par', models.BooleanField(default=False, verbose_name='Флаг формы')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.particleshape', verbose_name='Форма')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype', verbose_name='Тип порошка')),
            ],
            options={
                'verbose_name': 'Форма частиц порошка',
                'verbose_name_plural': 'Формы частиц порошка',
            },
        ),
        migrations.CreateModel(
            name='PowderAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_of', to='IACAPaaS_interactions.powdertype', verbose_name='Аналог')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='IACAPaaS_interactions.powdertype', verbose_name='Порошок')),
            ],
            options={
                'verbose_name': 'Аналог порошка',
                'verbose_name_plural': 'Аналоги порошков',
            },
        ),
        migrations.CreateModel(
            name='PropertySynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Синоним')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.property', verbose_name='Свойство')),
            ],
            options={
                'verbose_name': 'Синоним свойства',
                'verbose_name_plural': 'Синонимы свойств',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текстовое значение')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.property', verbose_name='Свойство')),
                ('property_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.propertyvaluetype', verbose_name='Тип значения')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IACAPaaS_interactions.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Значение свойства',
                'verbose_name_plural': 'Значения свойств',
            },
        ),
        migrations.CreateModel(
            name='PowderProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype', verbose_name='Тип порошка')),
                ('property_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.propertyvalue', verbose_name='Значение свойства')),
            ],
            options={
                'verbose_name': 'Свойство порошка',
                'verbose_name_plural': 'Свойства порошков',
            },
        ),
        migrations.CreateModel(
            name='MetalWireProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_wire', models.CharField(max_length=200, verbose_name='Источник')),
                ('date_wire', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('wire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.metalwire', verbose_name='Проволока')),
                ('property_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.propertyvalue', verbose_name='Значение свойства')),
            ],
            options={
                'verbose_name': 'Свойство проволоки',
                'verbose_name_plural': 'Свойства проволоки',
            },
        ),
        migrations.AddField(
            model_name='metalwire',
            name='diameter_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit', verbose_name='Единица измерения диаметра'),
        ),
        migrations.CreateModel(
            name='GranulometricComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('d10', models.FloatField(verbose_name='D10')),
                ('d50', models.FloatField(verbose_name='D50')),
                ('d90', models.FloatField(verbose_name='D90')),
                ('average_value', models.FloatField(verbose_name='Среднее значение')),
                ('mass_fraction', models.FloatField(verbose_name='Массовая доля')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype', verbose_name='Тип порошка')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Гранулометрический состав',
                'verbose_name_plural': 'Гранулометрический состав',
            },
        ),
        migrations.CreateModel(
            name='GasMixtureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField(verbose_name='Концентрация')),
                ('gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.gas', verbose_name='Газ')),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.gasmixture', verbose_name='Смесь')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Компонент газовой смеси',
                'verbose_name_plural': 'Компоненты газовых смесей',
            },
        ),
        migrations.CreateModel(
            name='Flowability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('bool_fil', models.BooleanField(default=False, verbose_name='Флаг заполнения')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype', verbose_name='Тип порошка')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Сыпучесть',
                'verbose_name_plural': 'Сыпучесть',
            },
        ),
        migrations.CreateModel(
            name='BulkDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('powder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.powdertype', verbose_name='Тип порошка')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACAPaaS_interactions.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Насыпная плотность',
                'verbose_name_plural': 'Насыпная плотность',
            },
        ),
        migrations.CreateModel(
            name='WireAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_of', to='IACAPaaS_interactions.metalwire', verbose_name='Аналог')),
                ('wire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='IACAPaaS_interactions.metalwire', verbose_name='Проволока')),
            ],
            options={
                'verbose_name': 'Аналог проволоки',
                'verbose_name_plural': 'Аналоги проволоки',
            },
        ),
    ]
